name: deploy

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          
      - name: Install dependencies
        run: npm install
        
      - name: Build with Next.js
        run: npm run next build
        
      - name: Build
        run: npm run build
        
      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
